First, a bit of a hack in case your IDE wants to run the notebook from `/material/` and not the project root folder `/ma1`. We need the working directory to be `/ma1` for local imports to work.

In [2]:
import os
from pathlib import Path

# Ensure the working directory is set to the "ma1" folder.
while Path.cwd().name != "ma1" and "ma1" in str(Path.cwd()):
    os.chdir("..")  # Move up one directory
print(f"Working directory set to: {Path.cwd()}")

Working directory set to: /Users/mikkel/Library/CloudStorage/OneDrive-Personligt/CBS/Cand Merc IT/2. Semester/AI and ML/mas/ma1


***

# Introduction to PyTorch Tensors

<img src="../media/tensor.png" width="500"/>

Tensors are the central data abstraction in PyTorch. This interactive
notebook provides an in-depth introduction to the `torch.Tensor` class. You can also watch a video on it on 
[youtube](https://www.youtube.com/watch?v=r7QDUPb2dCM).

First things first, let's import the PyTorch module. We'll also add
Python's math module to facilitate some of the examples.


In [3]:
import torch
import math

### Creating Tensors

The simplest way to create a tensor is with the `torch.empty()` call:


In [4]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Let's unpack what we just did:

-   We created a tensor using one of the numerous factory methods
    attached to the `torch` module.
-   The tensor itself is 2-dimensional, having 3 rows and 4 columns.
-   The type of the object returned is `torch.Tensor`, which is an alias
    for `torch.FloatTensor`; by default, PyTorch tensors are populated
    with 32-bit floating point numbers. (More on data types below.)
-   You will probably see some random-looking values when printing your
    tensor. The `torch.empty()` call allocates memory for the tensor,
    but does not initialize it with any values - so what you're seeing
    is whatever was in memory at the time of allocation.

A brief note about tensors and their number of dimensions, and
terminology:

-   You will sometimes see a 1-dimensional tensor called a *vector.*
-   Likewise, a 2-dimensional tensor is often referred to as a *matrix.*
-   Anything with more than two dimensions is generally just called a
    tensor.

More often than not, you'll want to initialize your tensor with some
value. Common cases are all zeros, all ones, or random values, and the
`torch` module provides factory methods for all of these:


In [5]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


The factory methods all do just what you'd expect - we have a tensor
full of zeros, another full of ones, and another with random values
between 0 and 1.

### Random Tensors and Seeding

Speaking of the random tensor, did you notice the call to
`torch.manual_seed()` immediately preceding it? Initializing tensors,
such as a model's learning weights, with random values is common but
there are times - especially in research settings - where you'll want
some assurance of the reproducibility of your results. Manually setting
your random number generator's seed is the way to do this. Let's look
more closely:


In [7]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2,3,4)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[[0.2332, 0.4047, 0.2162, 0.9927],
         [0.4128, 0.5938, 0.6128, 0.1519],
         [0.0453, 0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384, 0.4759],
         [0.7481, 0.0361, 0.5062, 0.8469],
         [0.2588, 0.2707, 0.4115, 0.6839]]])


What you should see above is that `random1` and `random3` carry
identical values, as do `random2` and `random4`. Manually setting the
RNG's seed resets it, so that identical computations depending on random
number should, in most settings, provide identical results.

For more information, see the [PyTorch documentation on
reproducibility](https://pytorch.org/docs/stable/notes/randomness.html).

### Tensor Shapes

Often, when you're performing operations on two or more tensors, they
will need to be of the same *shape* - that is, having the same number of
dimensions and the same number of cells in each dimension. For that, we
have the `torch.*_like()` methods:


In [4]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


The first new thing in the code cell above is the use of the `.shape`
property on a tensor. This property contains a list of the extent of
each dimension of a tensor - in our case, `x` is a three-dimensional
tensor with shape 2 x 2 x 3.

Below that, we call the `.empty_like()`, `.zeros_like()`,
`.ones_like()`, and `.rand_like()` methods. Using the `.shape` property,
we can verify that each of these methods returns a tensor of identical
dimensionality and extent.

The last way to create a tensor that will cover is to specify its data
directly from a PyTorch collection:


In [9]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


Using `torch.tensor()` is the most straightforward way to create a
tensor if you already have data in a Python tuple or list. As shown
above, nesting the collections will result in a multi-dimensional
tensor.

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p><code>torch.tensor()</code> creates a copy of the data.</p>

</div>

### Tensor Data Types

Setting the datatype of a tensor is possible a couple of ways:


In [11]:
a = torch.ones(2, 3, dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 9.8370,  3.8937, 16.1945],
        [12.3902, 15.0541, 16.8179]], dtype=torch.float64)
tensor([[ 9,  3, 16],
        [12, 15, 16]], dtype=torch.int32)


The simplest way to set the underlying data type of a tensor is with an
optional argument at creation time. In the first line of the cell above,
we set `dtype=torch.int16` for the tensor `a`. When we print `a`, we can
see that it's full of `1` rather than `1.` - Python's subtle cue that
this is an integer type rather than floating point.

Another thing to notice about printing `a` is that, unlike when we left
`dtype` as the default (32-bit floating point), printing the tensor also
specifies its `dtype`.

You may have also spotted that we went from specifying the tensor's
shape as a series of integer arguments, to grouping those arguments in a
tuple. This is not strictly necessary - PyTorch will take a series of
initial, unlabeled integer arguments as a tensor shape - but when adding
the optional arguments, it can make your intent more readable.

The other way to set the datatype is with the `.to()` method. In the
cell above, we create a random floating point tensor `b` in the usual
way. Following that, we create `c` by converting `b` to a 32-bit integer
with the `.to()` method. Note that `c` contains all the same values as
`b`, but truncated to integers.

For more information, see the [data types
documentation](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype).

### Math & Logic with PyTorch Tensors

Now that you know some of the ways to create a tensor... what can you do
with them?

Let's look at basic arithmetic first, and how tensors interact with
simple scalars:


In [12]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


As you can see above, arithmetic operations between tensors and scalars,
such as addition, subtraction, multiplication, division, and
exponentiation are distributed over every element of the tensor. Because
the output of such an operation will be a tensor, you can chain them
together with the usual operator precedence rules, as in the line where
we create `threes`.

Similar operations between two tensors also behave like you'd
intuitively expect:


In [13]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


It's important to note here that all of the tensors in the previous code
cell were of identical shape. What happens when we try to perform a
binary operation on tensors if dissimilar shape?

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>The following cell throws a run-time error. This is intentional.<pre><code>a = torch.rand(2, 3)
b = torch.rand(3, 2)</p>
<p>print(a * b)</code></pre></p>

</div>



In the general case, you cannot operate on tensors of different shape
this way, even in a case like the cell above, where the tensors have an
identical number of elements.

### In Brief: Tensor Broadcasting

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>If you are familiar with broadcasting semantics in NumPyndarrays, you’ll find the same rules apply here.</p>

</div>

The exception to the same-shapes rule is *tensor broadcasting.* Here's
an example:


In [14]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.7357, 0.0381, 0.2138, 0.5395],
        [0.3686, 0.4007, 0.7220, 0.8217]])
tensor([[1.4715, 0.0762, 0.4276, 1.0791],
        [0.7371, 0.8014, 1.4439, 1.6434]])


What's the trick here? How is it we got to multiply a 2x4 tensor by a
1x4 tensor?

Broadcasting is a way to perform an operation between tensors that have
similarities in their shapes. In the example above, the one-row,
four-column tensor is multiplied by *both rows* of the two-row,
four-column tensor.

This is an important operation in Deep Learning. The common example is
multiplying a tensor of learning weights by a *batch* of input tensors,
applying the operation to each instance in the batch separately, and
returning a tensor of identical shape - just like our (2, 4) \* (1, 4)
example above returned a tensor of shape (2, 4).

The rules for broadcasting are:

-   Each tensor must have at least one dimension - no empty tensors.
-   Comparing the dimension sizes of the two tensors, *going from last
    to first:*
    -   Each dimension must be equal, *or*
    -   One of the dimensions must be of size 1, *or*
    -   The dimension does not exist in one of the tensors

Tensors of identical shape, of course, are trivially "broadcastable", as
you saw earlier.

Here are some examples of situations that honor the above rules and
allow broadcasting:


In [15]:
a = torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.2612, 0.7375],
         [0.8328, 0.8444],
         [0.2941, 0.3788]],

        [[0.2612, 0.7375],
         [0.8328, 0.8444],
         [0.2941, 0.3788]],

        [[0.2612, 0.7375],
         [0.8328, 0.8444],
         [0.2941, 0.3788]],

        [[0.2612, 0.7375],
         [0.8328, 0.8444],
         [0.2941, 0.3788]]])
tensor([[[0.4567, 0.4567],
         [0.0649, 0.0649],
         [0.6677, 0.6677]],

        [[0.4567, 0.4567],
         [0.0649, 0.0649],
         [0.6677, 0.6677]],

        [[0.4567, 0.4567],
         [0.0649, 0.0649],
         [0.6677, 0.6677]],

        [[0.4567, 0.4567],
         [0.0649, 0.0649],
         [0.6677, 0.6677]]])
tensor([[[0.7826, 0.1332],
         [0.7826, 0.1332],
         [0.7826, 0.1332]],

        [[0.7826, 0.1332],
         [0.7826, 0.1332],
         [0.7826, 0.1332]],

        [[0.7826, 0.1332],
         [0.7826, 0.1332],
         [0.7826, 0.1332]],

        [[0.7826, 0.1332],
         [0.7826, 0.1332],
         [0.7826, 0.1332]]])


Look closely at the values of each tensor above:

-   The multiplication operation that created `b` was broadcast over
    every "layer" of `a`.
-   For `c`, the operation was broadcast over every layer and row of
    `a` - every 3-element column is identical.
-   For `d`, we switched it around - now every *row* is identical,
    across layers and columns.

For more information on broadcasting, see the [PyTorch
documentation](https://pytorch.org/docs/stable/notes/broadcasting.html)
on the topic.

Here are some examples of attempts at broadcasting that will fail:

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>The following cell throws a run-time error. This is intentional.<pre><code>a =     torch.ones(4, 3, 2)</p>
<p>b = a * torch.rand(4, 3)    # dimensions must match last-to-first</p>
<p>c = a * torch.rand(   2, 3) # both 3rd &amp; 2nd dims different</p>
<p>d = a * torch.rand((0, ))   # can&#x27;t broadcast with an empty tensor</code></pre></p>

</div>



### More Math with Tensors

PyTorch tensors have over three hundred operations that can be performed
on them.

Here is a small sample from some of the major categories of operations:


In [16]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.linalg.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.9955, 0.0110, 0.2285, 0.9767],
        [0.0476, 0.4484, 0.8447, 0.1992]])
tensor([[-0., -0., -0., 1.],
        [-0., 1., -0., -0.]])
tensor([[-1., -1., -1.,  0.],
        [-1.,  0., -1., -1.]])
tensor([[-0.5000, -0.0110, -0.2285,  0.5000],
        [-0.0476,  0.4484, -0.5000, -0.1992]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.9877, 0.0352],
        [0.0905, 0.4485]])
tensor([[2.9632, 0.1057],
        [0.2715, 1.3456]])
torch.return_types.linalg_svd(
U=tensor([[-0.9911, -0.1334],
        [-0.1334,  0.9911]]),
S=tensor([2.9865, 1.3255]),
Vh=tensor([[-0.9955, -0.0952],
        [-0.0952,  0.995

This is a small sample of operations. For more details and the full
inventory of math functions, have a look at the
[documentation](https://pytorch.org/docs/stable/torch.html#math-operations).
For more details and the full inventory of linear algebra operations,
have a look at this
[documentation](https://pytorch.org/docs/stable/linalg.html).

### Altering Tensors in Place

Most binary operations on tensors will return a third, new tensor. When
we say `c = a * b` (where `a` and `b` are tensors), the new tensor `c`
will occupy a region of memory distinct from the other tensors.

There are times, though, that you may wish to alter a tensor in place
-for example, if you're doing an element-wise computation where you can
discard intermediate values. For this, most of the math functions have a
version with an appended underscore (`_`) that will alter a tensor in
place.

For example:


In [17]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


For arithmetic operations, there are functions that behave similarly:


In [18]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8740, 0.2526],
        [0.6923, 0.7545]])

After adding:
tensor([[1.8740, 1.2526],
        [1.6923, 1.7545]])
tensor([[1.8740, 1.2526],
        [1.6923, 1.7545]])
tensor([[0.8740, 0.2526],
        [0.6923, 0.7545]])

After multiplying
tensor([[0.7638, 0.0638],
        [0.4793, 0.5693]])
tensor([[0.7638, 0.0638],
        [0.4793, 0.5693]])


Note that these in-place arithmetic functions are methods on the
`torch.Tensor` object, not attached to the `torch` module like many
other functions (e.g., `torch.sin()`). As you can see from `a.add_(b)`,
*the calling tensor is the one that gets changed in place.*

There is another option for placing the result of a computation in an
existing, allocated tensor. Many of the methods and functions we've seen
so far - including creation methods! - have an `out` argument that lets
you specify a tensor to receive the output. If the `out` tensor is the
correct shape and `dtype`, this can happen without a new memory
allocation:


In [19]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.5299, 0.4925],
        [1.1893, 0.5440]])
tensor([[0.5183, 0.9807],
        [0.6545, 0.4144]])


### Copying Tensors

As with any object in Python, assigning a tensor to a variable makes the
variable a *label* of the tensor, and does not copy it. For example:


In [20]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


But what if you want a separate copy of the data to work on? The
`clone()` method is there for you:


In [21]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


**There is an important thing to be aware of when using
\`\`clone()\`\`.** If your source tensor has autograd, enabled then so
will the clone. **This will be covered more deeply in the video on
autograd,** but if you want the light version of the details, continue
on.

*In many cases, this will be what you want.* For example, if your model
has multiple computation paths in its `forward()` method, and *both* the
original tensor and its clone contribute to the model's output, then to
enable model learning you want autograd turned on for both tensors. If
your source tensor has autograd enabled (which it generally will if it's
a set of learning weights or derived from a computation involving the
weights), then you'll get the result you want.

On the other hand, if you're doing a computation where *neither* the
original tensor nor its clone need to track gradients, then as long as
the source tensor has autograd turned off, you're good to go.

*There is a third case,* though: Imagine you're performing a computation
in your model's `forward()` function, where gradients are turned on for
everything by default, but you want to pull out some values mid-stream
to generate some metrics. In this case, you *don't* want the cloned copy
of your source tensor to track gradients - performance is improved with
autograd's history tracking turned off. For this, you can use the
`.detach()` method on the source tensor:


In [22]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.0696, 0.4648],
        [0.4491, 0.6265]], requires_grad=True)
tensor([[0.0696, 0.4648],
        [0.4491, 0.6265]], grad_fn=<CloneBackward0>)
tensor([[0.0696, 0.4648],
        [0.4491, 0.6265]])
tensor([[0.0696, 0.4648],
        [0.4491, 0.6265]], requires_grad=True)


What's happening here?

-   We create `a` with `requires_grad=True` turned on. **We haven't
    covered this optional argument yet, but will during the unit on
    autograd.**
-   When we print `a`, it informs us that the property
    `requires_grad=True` - this means that autograd and computation
    history tracking are turned on.
-   We clone `a` and label it `b`. When we print `b`, we can see that
    it's tracking its computation history - it has inherited `a`'s
    autograd settings, and added to the computation history.
-   We clone `a` into `c`, but we call `detach()` first.
-   Printing `c`, we see no computation history, and no
    `requires_grad=True`.

The `detach()` method *detaches the tensor from its computation
history.* It says, "do whatever comes next as if autograd was off." It
does this *without* changing `a` - you can see that when we print `a`
again at the end, it retains its `requires_grad=True` property.

### Moving to GPU

One of the major advantages of PyTorch is its robust acceleration on
CUDA-compatible Nvidia GPUs. ("CUDA" stands for *Compute Unified Device
Architecture*, which is Nvidia's platform for parallel computing.) So
far, everything we've done has been on CPU. How do we move to the faster
hardware?

First, we should check whether a GPU is available, with the
`is_available()` method.

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>If you do not have a CUDA-compatible GPU and CUDA driversinstalled, the executable cells in this section will not execute anyGPU-related code.</p>

</div>



In [23]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


Once we've determined that one or more GPUs is available, we need to put
our data someplace where the GPU can see it. Your CPU does computation
on data in your computer's RAM. Your GPU has dedicated memory attached
to it. Whenever you want to perform a computation on a device, you must
move *all* the data needed for that computation to memory accessible by
that device. (Colloquially, "moving the data to memory accessible by the
GPU" is shorted to, "moving the data to the GPU".)

There are multiple ways to get your data onto your target device. You
may do it at creation time:


In [24]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


By default, new tensors are created on the CPU, so we have to specify
when we want to create our tensor on the GPU with the optional `device`
argument. You can see when we print the new tensor, PyTorch informs us
which device it's on (if it's not on CPU).

You can query the number of GPUs with `torch.cuda.device_count()`. If
you have more than one GPU, you can specify them by index:
`device='cuda:0'`, `device='cuda:1'`, etc.

As a coding practice, specifying our devices everywhere with string
constants is pretty fragile. In an ideal world, your code would perform
robustly whether you're on CPU or GPU hardware. You can do this by
creating a device handle that can be passed to your tensors instead of a
string:


In [25]:
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.9411, 0.4922],
        [0.5461, 0.5396]])


If you have an existing tensor living on one device, you can move it to
another with the `to()` method. The following line of code creates a
tensor on CPU, and moves it to whichever device handle you acquired in
the previous cell.


In [26]:
y = torch.rand(2, 2)
y = y.to(my_device)

It is important to know that in order to do computation involving two or
more tensors, *all of the tensors must be on the same device*. The
following code will throw a runtime error, regardless of whether you
have a GPU device available:

``` {.python}
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='gpu')
z = x + y  # exception will be thrown
```


### Manipulating Tensor Shapes

Sometimes, you'll need to change the shape of your tensor. Below, we'll
look at a few common cases, and how to handle them.

#### Changing the Number of Dimensions

One case where you might need to change the number of dimensions is
passing a single instance of input to your model. PyTorch models
generally expect *batches* of input.

For example, imagine having a model that works on 3 x 226 x 226 images
-a 226-pixel square with 3 color channels. When you load and transform
it, you'll get a tensor of shape `(3, 226, 226)`. Your model, though, is
expecting input of shape `(N, 3, 226, 226)`, where `N` is the number of
images in the batch. So how do you make a batch of one?


In [27]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


The `unsqueeze()` method adds a dimension of extent 1. `unsqueeze(0)`
adds it as a new zeroth dimension - now you have a batch of one!

So if that's *un*squeezing? What do we mean by squeezing? We're taking
advantage of the fact that any dimension of extent 1 *does not* change
the number of elements in the tensor.


In [28]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.7349]]]]])


Continuing the example above, let's say the model's output is a
20-element vector for each input. You would then expect the output to
have shape `(N, 20)`, where `N` is the number of instances in the input
batch. That means that for our single-input batch, we'll get an output
of shape `(1, 20)`.

What if you want to do some *non-batched* computation with that output
-something that's just expecting a 20-element vector?


In [29]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.7823, 0.8637, 0.1891, 0.3952, 0.9176, 0.8960, 0.4887, 0.8625, 0.6191,
         0.9935, 0.1844, 0.6138, 0.6854, 0.0438, 0.0636, 0.2884, 0.4362, 0.2368,
         0.1394, 0.1721]])
torch.Size([20])
tensor([0.7823, 0.8637, 0.1891, 0.3952, 0.9176, 0.8960, 0.4887, 0.8625, 0.6191,
        0.9935, 0.1844, 0.6138, 0.6854, 0.0438, 0.0636, 0.2884, 0.4362, 0.2368,
        0.1394, 0.1721])
torch.Size([2, 2])
torch.Size([2, 2])


You can see from the shapes that our 2-dimensional tensor is now
1-dimensional, and if you look closely at the output of the cell above
you'll see that printing `a` shows an "extra" set of square brackets
`[]` due to having an extra dimension.

You may only `squeeze()` dimensions of extent 1. See above where we try
to squeeze a dimension of size 2 in `c`, and get back the same shape we
started with. Calls to `squeeze()` and `unsqueeze()` can only act on
dimensions of extent 1 because to do otherwise would change the number
of elements in the tensor.

Another place you might use `unsqueeze()` is to ease broadcasting.
Recall the example above where we had the following code:

``` {.python}
a = torch.ones(4, 3, 2)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)
```

The net effect of that was to broadcast the operation over dimensions 0
and 2, causing the random, 3 x 1 tensor to be multiplied element-wise by
every 3-element column in `a`.

What if the random vector had just been 3-element vector? We'd lose the
ability to do the broadcast, because the final dimensions would not
match up according to the broadcasting rules. `unsqueeze()` comes to the
rescue:


In [40]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
print(b)
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

tensor([0.4084, 0.3970, 0.8607])
torch.Size([3, 1])
tensor([[[0.4084, 0.4084],
         [0.3970, 0.3970],
         [0.8607, 0.8607]],

        [[0.4084, 0.4084],
         [0.3970, 0.3970],
         [0.8607, 0.8607]],

        [[0.4084, 0.4084],
         [0.3970, 0.3970],
         [0.8607, 0.8607]],

        [[0.4084, 0.4084],
         [0.3970, 0.3970],
         [0.8607, 0.8607]]])


The `squeeze()` and `unsqueeze()` methods also have in-place versions,
`squeeze_()` and `unsqueeze_()`:


In [42]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)
print(batch_me)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])
tensor([[[[0.8015, 0.2721, 0.0668,  ..., 0.8233, 0.7791, 0.1413],
          [0.5373, 0.0961, 0.0816,  ..., 0.4574, 0.6400, 0.0606],
          [0.4447, 0.1241, 0.1663,  ..., 0.4177, 0.8514, 0.9053],
          ...,
          [0.7053, 0.0897, 0.8082,  ..., 0.4174, 0.6594, 0.4704],
          [0.2397, 0.9546, 0.7989,  ..., 0.3748, 0.8168, 0.0998],
          [0.5082, 0.2464, 0.1459,  ..., 0.2319, 0.5689, 0.0838]],

         [[0.0705, 0.9183, 0.4772,  ..., 0.5823, 0.7120, 0.1549],
          [0.8686, 0.3161, 0.6862,  ..., 0.8122, 0.2626, 0.9888],
          [0.2290, 0.0634, 0.7592,  ..., 0.6597, 0.0088, 0.9960],
          ...,
          [0.0131, 0.0844, 0.6889,  ..., 0.6049, 0.0069, 0.6035],
          [0.8077, 0.3262, 0.5364,  ..., 0.8417, 0.7713, 0.8816],
          [0.0309, 0.9623, 0.1334,  ..., 0.9367, 0.6626, 0.8406]],

         [[0.2517, 0.7965, 0.5047,  ..., 0.1868, 0.2138, 0.2842],
          [0.9688, 0.6702, 0.5767,  ..., 0.0491, 0.96

Sometimes you'll want to change the shape of a tensor more radically,
while still preserving the number of elements and their contents. One
case where this happens is at the interface between a convolutional
layer of a model and a linear layer of the model - this is common in
image classification models. A convolution kernel will yield an output
tensor of shape *features x width x height,* but the following linear
layer expects a 1-dimensional input. `reshape()` will do this for you,
provided that the dimensions you request yield the same number of
elements as the input tensor has:


In [45]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)
print(output3d)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)
print(input1d)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
tensor([[[2.5992e-02, 4.0729e-01, 5.8757e-02,  ..., 8.0471e-01,
          5.3257e-01, 5.0729e-01],
         [9.6643e-01, 1.3561e-01, 8.6105e-01,  ..., 6.4388e-01,
          2.9143e-01, 5.7332e-01],
         [9.4762e-01, 8.4168e-02, 8.3906e-01,  ..., 3.2411e-01,
          5.1960e-01, 8.8413e-01],
         ...,
         [4.2678e-01, 8.8286e-01, 6.7122e-01,  ..., 7.6845e-01,
          2.0785e-01, 7.2476e-01],
         [7.7540e-02, 8.2760e-01, 5.5843e-01,  ..., 6.1894e-01,
          3.3371e-01, 2.0145e-01],
         [8.3400e-01, 9.5304e-01, 6.1920e-01,  ..., 7.8263e-01,
          7.4960e-01, 6.3354e-01]],

        [[5.6892e-01, 6.2150e-01, 9.0335e-01,  ..., 8.1805e-01,
          5.1241e-01, 4.2540e-01],
         [5.6950e-01, 9.3065e-01, 7.5793e-01,  ..., 8.8222e-01,
          3.9998e-01, 2.8208e-01],
         [6.6586e-01, 4.4245e-01, 7.4440e-02,  ..., 4.6383e-01,
          9.5544e-01, 9.1299e-01],
         ...,
         [6.7540e-01, 3.2257e-01, 3.2857e-01,  ..., 5.6

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>The <code>(6 * 20 * 20,)</code> argument in the final line of the cell above is because PyTorch expects a  when specifying atensor shape - but when the shape is the first argument of a method, itlets us cheat and just use a series of integers. Here, we had to add theparentheses and comma to convince the method that this is really aone-element tuple.</p>

</div>

When it can, `reshape()` will return a *view* on the tensor to be
changed - that is, a separate tensor object looking at the same
underlying region of memory. *This is important:* That means any change
made to the source tensor will be reflected in the view on that tensor,
unless you `clone()` it.

There *are* conditions, beyond the scope of this introduction, where
`reshape()` has to return a tensor carrying a copy of the data. For more
information, see the
[docs](https://pytorch.org/docs/stable/torch.html#torch.reshape).


### NumPy Bridge

In the section above on broadcasting, it was mentioned that PyTorch's
broadcast semantics are compatible with NumPy's - but the kinship
between PyTorch and NumPy goes even deeper than that.

If you have existing ML or scientific code with data stored in NumPy
ndarrays, you may wish to express that same data as PyTorch tensors,
whether to take advantage of PyTorch's GPU acceleration, or its
efficient abstractions for building ML models. It's easy to switch
between ndarrays and PyTorch tensors:


In [46]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


PyTorch creates a tensor of the same shape and containing the same data
as the NumPy array, going so far as to keep NumPy's default 64-bit float
data type.

The conversion can just as easily go the other way:


In [47]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.2848, 0.5918, 0.2809],
        [0.0814, 0.5564, 0.8020]])
[[0.2847857  0.5918422  0.28090876]
 [0.08142006 0.55643046 0.8020046 ]]


It is important to know that these converted objects are using *the same
underlying memory* as their source objects, meaning that changes to one
are reflected in the other:


In [48]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.2847857   0.5918422   0.28090876]
 [ 0.08142006 17.          0.8020046 ]]
